### ISSUE TITLE
Omniscope.api reference

### ISSUE THREAD

**Issue by bluecombats** [visokio/omniscope-custom-blocks#2]
I saw on on "DBScan" script a reference to Omniscope.api what is this and where can I find out any information about it?  Can any info be put on the README.md i.e. location of it on your computer for instance

**Comment by nils-drechsel** [comment]
Hi,

The scripts that are in this repository represent community blocks within the Omniscope application (have a look at https://visokio.com/ and check out the sandboxes at https://visokio.com/try/ where you can play around with the app). 

They offer extra functionality and are accessible just like any other block from the block menu. If you execute one of the blocks, e.g. DBScan, Omniscope will install the Omniscope API for you. It provides methods to access and send data to Omniscope workflows and to retrieve block options.

Currently, we don't have extensive API references for the Omniscope API as this is a brand new feature which is still under heavy development. It is however just a matter of a short time before we'll publish such resources.

The README.md is meant to give an interested person on github some idea of what the block is doing. As such it should contain only general information and nothing user specific. At the moment I would simply follow what has been done for other blocks, but the format is not crucial.
